# games-app-backend PyInstaller spec

import sys
from pathlib import Path

_root = Path(SPECPATH).parent

a = Analysis(
    [str(_root / "run_server.py")],
    pathex=[str(_root)],
    binaries=[],
    datas=[
        (str(_root / "games-mcp" / "src" / "games_mcp"), "games_mcp"),
        (str(_root / "web_sota" / "dist"), "web_sota/dist"),
    ],
    hiddenimports=[
        "_strptime",
        "_datetime",
        "sqlite3",
        "_sqlite3",
        "netrc",
        "fastmcp",
        "mcp",
        "fastapi",
        "starlette",
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "h11",
        "httptools",
        "websockets",
        "aiohttp",
        "pydantic",
        "pydantic.deprecated.decorator",
        "firebase_admin",
        "python_dotenv",
        "cachetools",
        "beartype",
        "pytz",
        "jsonschema",
        "key_value",
        "games_mcp",
        "games_mcp.server",
        "games_mcp.config",
        "games_mcp.database",
        "games_mcp.services.db_service",
        "games_mcp.services.engine_service",
        "games_mcp.services.game_service",
        "games_mcp.services.sync_service",
        "games_mcp.services.ai.heuristics",
        "games_mcp.services.ai.minimax",
        "games_mcp.tools.gameplay",
        "games_mcp.tools.analysis",
        "games_mcp.tools.management",
        "games_mcp.tools.orchestration",
        "server",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["torch", "torchvision", "torchaudio", "tensorboard", "numpy"],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="games-app-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
